// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxocigccqeemepkvkvin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4b2NpZ2NjcWVlbWVwa3ZrdmluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NDAzODYsImV4cCI6MjA3NDMxNjM4Nn0.Am3O4ntcVkCNBMXDzAu1xJdvswwJ-aSeLRrw_-wQRn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});